### PR TITLE
Fix/ci

### PR DESCRIPTION
**Pull request by theavege**
Hot fix

### CODE REVIEW

**Comment by theavege** [comment]
@Al-Muhandis Could you accept the PR?

**Comment by Al-Muhandis** [comment]
> @Al-Muhandis Could you accept the PR?

I did it a long time ago. But the strange thing is: the circle has been spinning for many days after pressing the Merge button and nothing is done. I can't press now disabled merge pull request button

**Comment by Al-Muhandis** [comment]
https://github.com/Al-Muhandis/ChGK_Timer/commit/6f92ed9f5bafcd60c11ce206e88bc191fccca6f7

**Comment by theavege** [comment]
> > @Al-Muhandis Could you accept the PR?
> 
> I did it a long time ago. But the strange thing is: the circle has been spinning for many days after pressing the Merge button and nothing is done. I can't press now disabled merge pull request button

I think It's GitHub's bug. I deleted my fork.

**Pull request closed without merging**
